name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AWS_S3_BUCKET: testbucket
      AWS_S3_ACCESS_KEY: minioadmin
      AWS_S3_SECRET_KEY: minioadmin
      AWS_S3_ENDPOINT: http://127.0.0.1:9000

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio \
            -e "MINIO_ACCESS_KEY=minioadmin" \
            -e "MINIO_SECRET_KEY=minioadmin" \
            -v /tmp/data:/data \
            -v /tmp/config:/root/.minio \
            minio/minio server /data

          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://testbucket

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Tests
        run: pytest