name: MinIO and Python Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-minio-and-python:
    runs-on: ubuntu-latest

    env:
      AWS_ENDPOINT_URL: "http://127.0.0.1:9000"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Start MinIO in Docker
        run: |
          docker run -d -p 9000:9000 --name minio \
            -e "MINIO_ACCESS_KEY=minioadmin" \
            -e "MINIO_SECRET_KEY=minioadmin" \
            -v /tmp/data:/data \
            -v /tmp/config:/root/.minio \
            minio/minio server /data
          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://test-bucket
      
      - name: Run Python script in Docker
        run: |
          echo """
          import os
          os.makedirs('assets', exist_ok=True)
          with open('assets/test.txt', 'w') as f:
              f.write('Hello, MinIO!')
          print('File created successfully.')
          os.system('aws --endpoint-url http://localhost:9000 s3 cp assets/test.txt s3://test-bucket/test.txt')
          """ > script.py
          docker run --rm --network=host -v $(pwd)/script.py:/script.py python:3.9 bash -c "pip install awscli && python /script.py"
